version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./database-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: numerical
      DB_PORT: 3306

  app:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - server